#!/usr/bin/env python3
"""Prepare or validate the qemu-eos work directory for EOS 2000D firmware 1.3.0."""

from __future__ import annotations

import argparse
import os
from pathlib import Path

CAMERA = "2000D"
FIRMWARE = "130"
ROM_FILES = ("ROM0.BIN", "ROM1.BIN")


def camera_dir(root: Path) -> Path:
    return root / CAMERA / FIRMWARE


def prepare(root: Path, create: bool, create_disks: bool) -> list[str]:
    cam = camera_dir(root)
    messages: list[str] = []

    if create:
        cam.mkdir(parents=True, exist_ok=True)
        messages.append(f"camera directory: {cam}")

    if create_disks:
        root.mkdir(parents=True, exist_ok=True)
        for name, size in (("sd.img", 64 * 1024 * 1024), ("cf.img", 16 * 1024 * 1024)):
            path = root / name
            if not path.exists():
                with path.open("wb") as handle:
                    handle.truncate(size)
                messages.append(f"created sparse {name}: {size} bytes")

    for name in ROM_FILES:
        path = cam / name
        if path.is_file():
            messages.append(f"found {path.name}: {path.stat().st_size} bytes")
        else:
            messages.append(f"MISSING {path}")

    return messages


def launch_command(root: Path, qemu_binary: str) -> str:
    return (
        f'QEMU_EOS_WORKDIR="{root}" "{qemu_binary}" '
        '-M 2000D,firmware=130 '
        f'-drive file="{root / "cf.img"}",if=ide,format=raw '
        f'-sd "{root / "sd.img"}" '
        '-serial stdio -display none -d io,int'
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "root",
        nargs="?",
        type=Path,
        default=Path(os.environ.get("QEMU_EOS_WORKDIR", ".")),
    )
    parser.add_argument("--create", action="store_true")
    parser.add_argument("--create-disks", action="store_true")
    parser.add_argument(
        "--qemu-binary",
        default="./arm-softmmu/qemu-system-arm",
        help="path to the patched qemu-system-arm binary",
    )
    parser.add_argument("--command", action="store_true", help="print a provisional launch command")
    args = parser.parse_args()

    messages = prepare(args.root, args.create, args.create_disks)
    for message in messages:
        print(message)

    missing = [camera_dir(args.root) / name for name in ROM_FILES
               if not (camera_dir(args.root) / name).is_file()]

    if args.command:
        print("\nProvisional launch command:")
        print(launch_command(args.root, args.qemu_binary))

    if missing:
        print(
            "\nROM0.BIN/ROM1.BIN are intentionally not generated by this tool. "
            "They must come from a verified firmware 1.3.0 extraction/dump."
        )
        return 2

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
