#!/usr/bin/env python3
"""Prepare or validate qemu-eos work directories for EOS 2000D firmware."""

from __future__ import annotations

import argparse
import hashlib
import os
from pathlib import Path

CAMERA = "2000D"
FIRMWARE = "130"
ROM_FILES = ("ROM0.BIN", "ROM1.BIN")
ROM1_110_SHA256 = "7c17f49c5521ffe2fa140371a1bcb6353874b94d5c2669982b86f35e639c1a12"


def camera_dir(root: Path, firmware: str = FIRMWARE) -> Path:
    if firmware not in {"110", "130"}:
        raise ValueError("supported firmware selectors: 110, 130")
    return root / CAMERA / firmware


def required_roms(firmware: str) -> tuple[str, ...]:
    return ("ROM1.BIN",) if firmware == "110" else ROM_FILES


def validate_roms(root: Path, firmware: str) -> list[str]:
    cam = camera_dir(root, firmware)
    errors = [f"MISSING {cam / name}" for name in required_roms(firmware)
              if not (cam / name).is_file()]
    if firmware == "110" and (cam / "ROM0.BIN").exists():
        errors.append("110 workdir must not contain the invalid ROM0 dump or a fabricated substitute")
    if firmware == "110" and (cam / "ROM1.BIN").is_file():
        path = cam / "ROM1.BIN"
        if path.stat().st_size != 0x02000000 or hashlib.sha256(path.read_bytes()).hexdigest() != ROM1_110_SHA256:
            errors.append("ROM1.BIN does not match the canonical 2000D 1.1.0 dump")
    return errors


def prepare(root: Path, create: bool, create_disks: bool, firmware: str = FIRMWARE) -> list[str]:
    cam = camera_dir(root, firmware)
    messages: list[str] = []

    if create:
        cam.mkdir(parents=True, exist_ok=True)
        messages.append(f"camera directory: {cam}")

    if create_disks:
        root.mkdir(parents=True, exist_ok=True)
        for name, size in (("sd.img", 64 * 1024 * 1024), ("cf.img", 16 * 1024 * 1024)):
            path = root / name
            if not path.exists():
                with path.open("wb") as handle:
                    handle.truncate(size)
                messages.append(f"created sparse {name}: {size} bytes")

    for name in required_roms(firmware):
        path = cam / name
        if path.is_file():
            messages.append(f"found {path.name}: {path.stat().st_size} bytes")
        else:
            messages.append(f"MISSING {path}")

    return messages


def launch_command(root: Path, qemu_binary: str, firmware: str = FIRMWARE,
                   start_main: bool = False) -> str:
    camera_dir(root, firmware)  # Validate selector even without directory creation.
    if start_main and firmware != "110":
        raise ValueError("direct main-entry experiment is available only for firmware 110")
    selector = firmware + (";start=main" if start_main else "")
    return (
        f'QEMU_EOS_WORKDIR="{root}" "{qemu_binary}" '
        f'-M "2000D,firmware={selector}" '
        f'-drive file="{root / "cf.img"}",if=ide,format=raw '
        f'-sd "{root / "sd.img"}" '
        '-serial stdio -display none -d io,int'
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "root",
        nargs="?",
        type=Path,
        default=Path(os.environ.get("QEMU_EOS_WORKDIR", ".")),
    )
    parser.add_argument("--create", action="store_true")
    parser.add_argument("--firmware", choices=["110", "130"], default=FIRMWARE)
    parser.add_argument("--start-main", action="store_true", help="110 only: bypass the absent reset bootloader")
    parser.add_argument("--create-disks", action="store_true")
    parser.add_argument(
        "--qemu-binary",
        default="./arm-softmmu/qemu-system-arm",
        help="path to the patched qemu-system-arm binary",
    )
    parser.add_argument("--command", action="store_true", help="print a provisional launch command")
    args = parser.parse_args()

    if args.start_main and args.firmware != "110":
        parser.error("--start-main requires --firmware 110")
    messages = prepare(args.root, args.create, args.create_disks, args.firmware)
    for message in messages:
        print(message)

    errors = validate_roms(args.root, args.firmware)

    if args.command:
        print("\nProvisional launch command:")
        print(launch_command(args.root, args.qemu_binary, args.firmware, args.start_main))

    if errors:
        for error in errors:
            print(error)
        print(
            "\nFirmware ROMs are never generated by this tool. "
            "110 requires the canonical ROM1 only; 130 still requires verified bank evidence."
        )
        return 2

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
